package io.inugami.framework.api.loggers.mdc.initializer;

import io.inugami.framework.api.tools.unit.test.api.SkipLineMatcher;
import org.junit.jupiter.api.Test;

import static io.inugami.framework.api.tools.unit.test.UnitTestHelper.assertText;

class DefaultMdcInitializerTest {

    @Test
    void getDefaultValue_nominal() {
        assertText(new DefaultMdcInitializer().getDefaultValue(),
                   """
                           {
                             "appClass" : "xxxx",
                             "appClassShortName" : "xxxx",
                             "appMethod" : "xxxx",
                             "appService" : "xxxx",
                             "appSubService" : "xxxx",
                             "applicationVersion" : "xxxx",
                             "asset" : "xxxx",
                             "artifactId" : "xxxx",
                             "authProtocol" : "xxxx",
                             "callFrom" : "xxxx",
                             "callType" : "xxxx",
                             "conversation_id" : "xxxx",
                             "correlation_id" : "xxxx",
                             "commitId" : "xxxx",
                             "commitDate" : "xxxx",
                             "country" : "xxxx",
                             "customerId" : "xxxx",
                             "deviceClass" : "xxxx",
                             "deviceIdentifier" : "xxxx",
                             "deviceIp" : "xxxx",
                             "deviceNetworkSpeedDown" : 0.0,
                             "deviceNetworkSpeedLatency" : 0.0,
                             "deviceNetworkSpeedUp" : 0.0,
                             "deviceNetworkType" : "xxxx",
                             "deviceType" : "xxxx",
                             "domain" : "xxxx",
                             "duration" : 0,
                             "env" : "xxxx",
                             "errorCategory" : "xxxx",
                             "errorCode" : "xxxx",
                             "errorExploitationError" : false,
                             "errorField" : "xxxx",
                             "errorMessage" : "xxxx",
                             "errorMessageDetail" : "xxxx",
                             "errorRetryable" : false,
                             "errorRollback" : false,
                             "errorStatus" : "xxxx",
                             "errorType" : "xxxx",
                             "errorUrl" : "xxxx",
                             "exceptionName" : "xxxx",
                             "errorDomain" : "xxxx",
                             "errorSubDomain" : "xxxx",
                             "flags" : "xxxx",
                             "from" : "2025-11-29T13:24:27.755505934",
                             "fromTimestamp" : 0,
                             "functionalUid" : "xxxx",
                             "globalStatus" : "xxxx",
                             "groupId" : "xxxx",
                             "healthStatus" : "up",
                             "hostname" : "xxxx",
                             "httpStatus" : 0,
                             "instanceName" : "xxxx",
                             "instanceNumber" : "xxxx",
                             "language" : "xxxx",
                             "lifecycle" : "xxxx",
                             "majorVersion" : "xxxx",
                             "messageId" : "xxxx",
                             "methodInCause" : "xxxx",
                             "orderId" : "xxxx",
                             "osVersion" : "xxxx",
                             "parentSpanId" : "xxxx",
                             "partner" : "xxxx",
                             "partnerRequestCharset" : "xxxx",
                             "partnerResponseCharset" : "xxxx",
                             "partnerResponseDuration" : 0,
                             "partnerResponseMessage" : "xxxx",
                             "partnerResponseStatus" : 0,
                             "partnerService" : "xxxx",
                             "partnerSubService" : "xxxx",
                             "partnerType" : "xxxx",
                             "partnerUrl" : "xxxx",
                             "partnerVerb" : "xxxx",
                             "price" : 0.0,
                             "principal" : "xxxx",
                             "productId" : "xxxx",
                             "processId" : "xxxx",
                             "processName" : "xxxx",
                             "processStatus" : "xxxx",
                             "quantity" : 0.0,
                             "remoteAddress" : "xxxx",
                             "requestHeaders" : "xxxx",
                             "request_id" : "xxxx",
                             "reservationNumber" : "xxxx",
                             "responseHeaders" : "xxxx",
                             "service" : "xxxx",
                             "sessionId" : "xxxx",
                             "size" : 0.0,
                             "traceId" : "xxxx",
                             "until" : "2025-11-29T13:24:27.759236054",
                             "untilTimestamp" : 0,
                             "uri" : "xxxx",
                             "url" : "xxxx",
                             "urlPattern" : "xxxx",
                             "userAgent" : "xxxx",
                             "userId" : "xxxx",
                             "status" : "xxxx",
                             "subDomain" : "xxxx",
                             "verb" : "xxxx",
                             "version" : "xxxx",
                             "warning" : "xxxx"
                           }
                           """,
                   SkipLineMatcher.of(44,89));
    }
}