package io.inugami.framework.api.loggers.mdc.initializer;

import io.inugami.framework.api.tools.unit.test.api.SkipLineMatcher;
import io.inugami.framework.interfaces.monitoring.MdcServiceSpi;
import org.junit.jupiter.api.Test;

import static io.inugami.framework.api.loggers.mdc.initializer.MdcInitializer.processInitialization;
import static io.inugami.framework.api.tools.unit.test.UnitTestHelper.assertText;

class MdcInitializerTest {

    @Test
    void initialize_nominal() {
        final MdcServiceSpi mdc = processInitialization();
        assertText(mdc.getAllMdc(),
                   """
                           {
                              "appClass" : "xxxx",
                              "appClassShortName" : "xxxx",
                              "appMethod" : "xxxx",
                              "appService" : "xxxx",
                              "appSubService" : "xxxx",
                              "applicationVersion" : "xxxx",
                              "artifactId" : "xxxx",
                              "asset" : "xxxx",
                              "authProtocol" : "xxxx",
                              "callFrom" : "xxxx",
                              "callType" : "xxxx",
                              "commitDate" : "xxxx",
                              "commitId" : "xxxx",
                              "conversation_id" : "xxxx",
                              "correlation_id" : "xxxx",
                              "country" : "xxxx",
                              "customerId" : "xxxx",
                              "deviceClass" : "xxxx",
                              "deviceIdentifier" : "xxxx",
                              "deviceIp" : "xxxx",
                              "deviceNetworkSpeedDown" : "0.0",
                              "deviceNetworkSpeedLatency" : "0.0",
                              "deviceNetworkSpeedUp" : "0.0",
                              "deviceNetworkType" : "xxxx",
                              "deviceType" : "xxxx",
                              "domain" : "xxxx",
                              "duration" : "0",
                              "env" : "xxxx",
                              "errorCategory" : "xxxx",
                              "errorCode" : "xxxx",
                              "errorDomain" : "xxxx",
                              "errorExploitationError" : "false",
                              "errorField" : "xxxx",
                              "errorMessage" : "xxxx",
                              "errorMessageDetail" : "xxxx",
                              "errorRetryable" : "false",
                              "errorRollback" : "false",
                              "errorStatus" : "xxxx",
                              "errorSubDomain" : "xxxx",
                              "errorType" : "xxxx",
                              "errorUrl" : "xxxx",
                              "exceptionName" : "xxxx",
                              "flags" : "xxxx",
                              "from" : "2026-01-08T08:51:12.000899145",
                              "fromTimestamp" : "0",
                              "functionalUid" : "xxxx",
                              "globalStatus" : "xxxx",
                              "groupId" : "xxxx",
                              "healthStatus" : "up",
                              "hostname" : "xxxx",
                              "httpStatus" : "0",
                              "instanceName" : "xxxx",
                              "instanceNumber" : "xxxx",
                              "language" : "xxxx",
                              "lifecycle" : "xxxx",
                              "majorVersion" : "xxxx",
                              "messageId" : "xxxx",
                              "methodInCause" : "xxxx",
                              "orderId" : "xxxx",
                              "osVersion" : "xxxx",
                              "parentSpanId" : "xxxx",
                              "partner" : "xxxx",
                              "partnerRequestCharset" : "xxxx",
                              "partnerResponseCharset" : "xxxx",
                              "partnerResponseDuration" : "0",
                              "partnerResponseMessage" : "xxxx",
                              "partnerResponseStatus" : "0",
                              "partnerService" : "xxxx",
                              "partnerSubService" : "xxxx",
                              "partnerType" : "xxxx",
                              "partnerUrl" : "xxxx",
                              "partnerVerb" : "xxxx",
                              "price" : "0.0",
                              "principal" : "xxxx",
                              "processId" : "xxxx",
                              "processName" : "xxxx",
                              "processStatus" : "xxxx",
                              "productId" : "xxxx",
                              "quantity" : "0.0",
                              "remoteAddress" : "xxxx",
                              "requestHeaders" : "xxxx",
                              "request_id" : "xxxx",
                              "reservationNumber" : "xxxx",
                              "responseHeaders" : "xxxx",
                              "service" : "xxxx",
                              "sessionId" : "xxxx",
                              "size" : "0.0",
                              "status" : "xxxx",
                              "subDomain" : "xxxx",
                              "traceId" : "xxxx",
                              "until" : "2026-01-08T08:51:12.001192079",
                              "untilTimestamp" : "0",
                              "uri" : "xxxx",
                              "url" : "xxxx",
                              "urlPattern" : "xxxx",
                              "urlPatternVerb" : "xxxx",
                              "userAgent" : "xxxx",
                              "userId" : "xxxx",
                              "verb" : "xxxx",
                              "version" : "xxxx",
                              "warning" : "xxxx"
                            }
                           """,
                   SkipLineMatcher.of(44, 91));
        MdcInitializer.initialize();
    }
}