<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!--================================================================================================================
    = MAVEN
    =================================================================================================================-->
    <prerequisites>
        <maven>3.2.3</maven>
    </prerequisites>

    <!--================================================================================================================
    = PARENT
    =================================================================================================================-->
    <parent>
        <groupId>${groupId}</groupId>
        <artifactId>${rootArtifactId}</artifactId>
        <version>${version}</version>
    </parent>


    <!--================================================================================================================
    = PROJECT
    =================================================================================================================-->
    <artifactId>${rootArtifactId}-infrastructure</artifactId>


    <!--================================================================================================================
    = DEPENDENCIES
    =================================================================================================================-->
    <dependencies>
        <dependency>
            <groupId>${groupId}</groupId>
            <artifactId>${rootArtifactId}-api</artifactId>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
        </dependency>

        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-jpa</artifactId>
            <classifier>jakarta</classifier>
            <version>${querydsl.version}</version>
        </dependency>

        <dependency>
            <groupId>io.inugami.framework</groupId>
            <artifactId>inugami_api_interfaces</artifactId>
        </dependency>

        <dependency>
            <groupId>io.inugami.framework</groupId>
            <artifactId>inugami_api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.inugami.framework.commons</groupId>
            <artifactId>inugami_commons</artifactId>
        </dependency>

        <dependency>
            <groupId>io.inugami.framework.commons</groupId>
            <artifactId>inugami_commons_spring</artifactId>
        </dependency>

        <dependency>
            <groupId>io.inugami.framework.commons</groupId>
            <artifactId>inugami_commons_spring_data</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jspecify</groupId>
            <artifactId>jspecify</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
        </dependency>

        <dependency>
            <groupId>io.inugami.framework.commons</groupId>
            <artifactId>inugami_commons_test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.skyscreamer</groupId>
                    <artifactId>jsonassert</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</project>
