<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>


    <!--================================================================================================================
    = PARENT
    =================================================================================================================-->
    <parent>
        <artifactId>inugami_common</artifactId>
        <groupId>io.inugami.framework.commons</groupId>
        <version>4.1.3-SNAPSHOT</version>
    </parent>

    <!--================================================================================================================
    = PROJECT
    =================================================================================================================-->
    <artifactId>inugami_common_components</artifactId>
    <name>${project.groupId}:${project.artifactId}</name>
    <url>http://inugami.io/inugami/inugami_common_components</url>

    <!--================================================================================================================
    = DEPENDENCIES
    =================================================================================================================-->
    <dependencies>
        <dependency>
            <groupId>io.inugami.framework</groupId>
            <artifactId>inugami_api</artifactId>
        </dependency>

        <dependency>
            <groupId>io.inugami.framework</groupId>
            <artifactId>inugami_api_interfaces</artifactId>
        </dependency>

        <dependency>
            <groupId>io.inugami.framework.commons</groupId>
            <artifactId>inugami_commons</artifactId>
        </dependency>


        <!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        + TEST
        +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
        <dependency>
            <groupId>io.inugami.framework.commons</groupId>
            <artifactId>inugami_commons_test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>